### ISSUE TITLE
неверно

### ISSUE THREAD

**Issue by Parapitek** [ArhipovaDaria2212/exam#1]
Задание по javascript выполнено неверно. Будьте внимательнее

**Comment by ArhipovaDaria2212** [comment]
Теперь должно быть правильно, буду внимательней)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

ср, 8 июн. 2022 г. в 13:23, Rustam Safarov ***@***.***>:

**Comment by Parapitek** [comment]
Всё равно вижу ошибку.
